version: "3"

services:

  db:
    build: db
    restart: on-failure
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      # No time mapping is needed, we expect the database to run in UTC.
    environment:
      - POSTGRES_USER=catmaid
      - POSTGRES_PASSWORD=catmaid_password
      - POSTGRES_DB=catmaid
      # By default, 50 connections are assumed.
      - DB_CONNECTIONS=50
      # By default, the database is only tuned on initial startup. To force a
      # new tuning, set DB_FORCE_TUNE=true.
      - DB_FORCE_TUNE=false
      # Allow database updates
      #- DB_UPDATE=false
      #
      # Enable initial tuning
      # - DB_TUNE=true
      #
      # By default the available memory of the host is used for tuning the
      # database. This can be overridden by setting INSTANCE_MEMORY to a custom
      # value in megabytes.
      #- INSTANCE_MEMORY=512

  app:
    image: catmaid/catmaid
    restart: unless-stopped
    volumes:
      - ./volumes/app/static:/home/django/static
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - DB_HOST=db
      - DB_USER=catmaid
      - DB_PASS=catmaid_password
      - DB_NAME=catmaid
      - CM_EXAMPLE_PROJECTS=true
    depends_on:
      - db

  web:
    build: web
    ports:
      - "8000:80"
      - "8443:443"
    restart: on-failure
    volumes:
      # This directory must have cert files
      - ./volumes/web/cert:/cert:ro
      - ./volumes/app/static:/static:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - app
